### PR TITLE
Changed the grade reports to new format

### PR DESCRIPTION
**Pull request by bhuvy2**
* Got rid of angularjs nonsense
* Use the template from the website
* Fixed the navbar at the top to avoid flooding autograde reports
* The code always uses the latest autograde using revision number
* Used cache busting on `results.json` so that every time a student loads, an uncached version is used
* When viewed offline or in a non-web browser, the report tells them to view on subversion

* Keeps the old functionality of revisions
* There are some design changes, please critique
* Needs to work on other devices (chrome on iphone 7)

### CODE REVIEW

**Comment by bhuvy2** [comment]
screenshot-2018-1-23 grade report 2

Here is a design for those who don't want to clone + run.

**Comment by bhuvy2** [comment]
@NavneethJayendran - I asked a review because we were talking about giving sliding timeouts, do you think we should include some new UI to support that or just leave it to individual tests in their output?

@earwig - Because of your eye for style 😄

**Comment by billlipeng** [comment]
Not sure if this is related, but if we have multiple runs for one assignment, eventually the timestamp is out of boundary. I can't scroll the bar on the left, nor can I scroll the bar on the top. It makes me very hard to access a specific timestamp. 
screen shot 2018-01-23 at 11 13 15 am

**Comment by bhuvy2** [comment]
Definitely, I fixed that by not having scrolling at all. All the timestamps are at the top and you click to switch between different ones. It is a bit of pain having to scroll up and down to view timestamps but it is more accessibility friendly and just easier css wise. Is there anything else you'd want in this @billlipeng ?

**Comment by billlipeng** [comment]
Awesome! Btw, have you tested the new page in a mobile browser?  Just to make sure the new page looks good on a smartphone.

**Comment by bhuvy2** [comment]
Yes! Thank you for reminding me. I will test that ASAP.

**Comment by bhuvy2** [comment]
Mobile:
screen shot 2018-01-23 at 11 27 53
screen shot 2018-01-23 at 11 27 59
screen shot 2018-01-23 at 11 28 10
screen shot 2018-01-23 at 11 28 16

Done!

**Comment by bhuvy2** [comment]
In my testing this works with all numbers of autogrades for nonstop networking. There is a weird issue for larger mobile devices and small tablets that needs to be resolved.

**Pull request merged**
